# Generated by Django 5.2.17 on 2026-09-02 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model_number', models.CharField(blank=True, max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('accuracy_class', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Verification Pending'), ('VALID', 'Valid'), ('EXPIRING', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('last_verified_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to=settings.AUTH_USER_MODEL)),
                ('instrument_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='core.instrumenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instrument_id'], name='core_instru_instrum_118492_idx'), models.Index(fields=['status'], name='core_instru_status_db7031_idx'), models.Index(fields=['owner'], name='core_instru_owner_i_be6d26_idx'), models.Index(fields=['next_due_date'], name='core_instru_next_du_ccaba9_idx')],
            },
        ),
    ]
