# Generated by Django 5.2.17 on 2026-09-02 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instrumenttype_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('verification_type', models.CharField(choices=[('INITIAL', 'Initial Verification'), ('REVERIFICATION', 'Re-verification')], max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_applications', to='core.instrument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application_number'], name='core_verifi_applica_877d6d_idx'), models.Index(fields=['status'], name='core_verifi_status_0b4309_idx'), models.Index(fields=['instrument'], name='core_verifi_instrum_0019d6_idx')],
            },
        ),
    ]
