# Generated by Django 5.2.17 on 2026-09-08 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_verificationapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='verificationapplication',
            name='core_verifi_instrum_0019d6_idx',
        ),
        migrations.AddField(
            model_name='verificationapplication',
            name='assigned_gatc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gatc_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationapplication',
            name='assigned_lmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lmo_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationapplication',
            name='assignment_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verificationapplication',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationapplication',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationapplication',
            name='application_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='verificationapplication',
            name='remarks',
            field=models.TextField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationapplication',
            name='verification_type',
            field=models.CharField(choices=[('INITIAL', 'Initial Verification'), ('REVERIFICATION', 'Re-Verification')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='verificationapplication',
            index=models.Index(fields=['application_date'], name='core_verifi_applica_7e8ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationapplication',
            index=models.Index(fields=['assigned_lmo'], name='core_verifi_assigne_11884c_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationapplication',
            index=models.Index(fields=['assigned_gatc'], name='core_verifi_assigne_b3dbec_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationapplication',
            index=models.Index(fields=['scheduled_date'], name='core_verifi_schedul_2fa2a2_idx'),
        ),
    ]
