# Generated by Django 5.2.17 on 2026-09-08 18:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_verificationapplication_core_verifi_instrum_0019d6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('PASS', 'Verified / Pass'), ('FAIL', 'Failed')], max_length=10)),
                ('instrument_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('observation', models.TextField()),
                ('measurement_details', models.TextField(blank=True)),
                ('capacity_verified', models.CharField(blank=True, max_length=100)),
                ('accuracy_observed', models.CharField(blank=True, max_length=100)),
                ('seal_condition', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location_address', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_record', to='core.verificationapplication')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='verification_files/%Y/%m/')),
                ('file_type', models.CharField(choices=[('PHOTO', 'Inspection Photo'), ('DOCUMENT', 'Supporting Document'), ('OTHER', 'Other')], default='PHOTO', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.verificationrecord')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('verification_token', models.CharField(default=uuid.uuid4, editable=False, max_length=80, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField()),
                ('certificate_status', models.CharField(default='VALID', max_length=20)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='certificates/qr/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='core.verificationrecord')),
            ],
        ),
    ]
