# Generated by Django 5.2.17 on 2026-09-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_verificationrecord_verificationfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
