# Generated by Django 6.1.1 on 2026-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_verificationrecord_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
